### PR TITLE
Fix compiler errors from old type hint field specification

### PR DESCRIPTION
**Pull request by asantas93**
Should fix https://github.com/json4s/json4s/runs/812152074

### CODE REVIEW

**Comment by mccartney** [comment]
Wait. How come #690 contained a compilation error? The PR builder said it was OK.

**Comment by mccartney** [comment]
Is it because #656 was merged in between?

**Comment by mccartney** [comment]
> Is it because #656 was merged in between?

We don't seem to have the branch-merged-to-master build for Travis, only the branch build (not sure what are the official Travis names for these notions). And this is why Travis didn't help us here.
