### ISSUE TITLE
Getting NoSuchMethodError with scala 2.12.10 and spark 3.2.0

### ISSUE THREAD

**Issue by ma6878** [json4s/json4s#1169]
### jdk: 1.8

I have been getting the following error: java.lang.NoSuchMethodError: org.json4s.JsonAST$JField$.unapply(Lscala/Tuple2;)Lscala/Tuple2

**Comment by veromos** [comment]
Hi,

I have similar issue after upgrading from : 
- scala 2.11 -> 2.12
- spark 2.4 -> 3.1 
- keeping json4s version 3.5.3

I have this error coming from spark : 
`"Exception in User Class: java.lang.NoSuchMethodError : org.json4s.JsonDSL$.seq2jvalue(Lscala/collection/Traversable;Lscala/Function1;)Lorg/json4s/JsonAST$JArray;"
`

After upgrading json4s 3.5.3 to 4.1.0-M2, I have the following new error : 
`Caused by: java.lang.ClassNotFoundException: org.json4s.JsonAST$JValue 
`

Any idea if there are incompabilities between spark or scala and json4s ?

**Comment by vietvudanh** [comment]
Same problem, anyone have insight on why?

**Comment by geoox** [comment]
Experiencing same issue as @veromos when bumping scala (2.11.12 -> 2.12.15) and spark (2.4.4 -> 3.3.2).
I managed to make it work by **not bumping** to json4s 4.x.x, but to **3.6.12**

**Comment by sm0217** [comment]
Anyone managed to resolve this?
